README.md
taskiq_redis/__init__.py
taskiq_redis/redis_broker.py

To solve [this issue](https://github.com/taskiq-python/taskiq-redis/issues/11), I suggest you use a standard List instead of PubSub. This allows you to use BRPOP to receive one message per worker.

Split Broker into Broadcast and Standart

---

tests/test_broker.py

I have to listen in order not to lose the message in PubSub

Some broker tests

---

taskiq_redis/redis_backend.py

This PR adds call of super().shutdown(), because it has important logic of running user's functions.

Updated shutdown method.

---

taskiq_redis/redis_broker.py

Closes https://github.com/taskiq-python/taskiq-redis/issues/29.

Add super.shutdown() call in redis brokers

---

taskiq_redis/redis_broker.py
tests/test_broker.py

Do not set url for BaseRedisBroker

---

.github/workflows/test.yml
docker-compose.yml
taskiq_redis/__init__.py
taskiq_redis/redis_backend.py
tests/conftest.py
tests/test_result_backend.py

This is a draft that adds redis cluster option for result backend.
This PR contains set up of redis cluster in CI, which can be used in further PRs (such as adding cluster mode support to broker).

Draft: Add cluster option to result backend

---

taskiq_redis/__init__.py
taskiq_redis/redis_cluster_broker.py
tests/test_broker.py

This PR includes updates to support the redis cluster option for the List Queue broker. The changes involve the addition of the BaseRedisClusterBroker and ListQueueClusterBroker.

implement redis cluster broker

---

.github/workflows/test.yml

This job might fail and it's not critical if it does.

Fixed codecov.

---

taskiq_redis/__init__.py
taskiq_redis/schedule_source.py
tests/test_schedule_source.py

Similarly to broker and backend, I added a cluster version of redis schedule source.
The implementation is in separate class. I also duplicated the tests of `RedisScheduleSource` and applied them to cluster source. I also added a few more tests for both `RedisScheduleSource` and `RedisClusterScheduleSource` and the `taskiq_redis.schedule_source` module is now completely covered.
There is no documentation for schedule sources yet, so I didn't touch it in this PR, but I'd like to find some time to add documentation about cluster mode in general and schedule sources in particular to README.

Add cluster schedule source

---

README.md
taskiq_redis/redis_backend.py
taskiq_redis/redis_broker.py
taskiq_redis/schedule_source.py
tests/test_broker.py
tests/test_result_backend.py
tests/test_schedule_source.py

Closes #53.
I decided not to add `timeout` argument at the moment, because any unknown argument passed to constructor is passed to the `BlockedConnectionPool` (including `timeout` if user wishes to customize it).
`BlockingConnectionPool` default is 20 seconds. If you think it's too high, we can still customize that value without changing constructors themselves, like this:
```python
if "timeout" not in connection_kwargs:
connection_kwargs["timeout"] = 3  # or other sensible default
```

Use blocking connection pool

---

taskiq_redis/redis_broker.py

Hello,
In some case, it can be very useful to set the `queue_name` directly in the label.
If we have several workers with different configurationse this avoids the need to create a broker and a scheduler for each type of worker. Instead, by putting the `queue_name` in the labels, the task will automatically be sent to the correct worker. And therefore a single scheduler can send the task to several workers.

feat(broker): allow to set queue name dynamically when kicking

---

taskiq_redis/schedule_source.py
tests/test_schedule_source.py

This PR removes MGET command from a cluster source, because it's not available in clustering mode.
Fixes: https://github.com/taskiq-python/taskiq-redis/issues/61

Fixed rediscluster schedule source.

---

.pre-commit-config.yaml
taskiq_redis/redis_backend.py
tests/test_result_backend.py

Uses as standard suffix on the redis key (hardcoded as "__progress") to store progress results.

feat: Add get_progress and set_progress to redis result backend

---

taskiq_redis/redis_broker.py

The issue is that if the connection is disrupted (due to a Redis restart or temporary connectivity issues), the Taskiq worker crashes, interrupting all ongoing handlers. For example, any long-running tasks will be interrupted and will not complete their work.

fix #65: avoid worker crash in case connection is broken

---

README.md
poetry.lock
pyproject.toml
taskiq_redis/__init__.py
taskiq_redis/list_schedule_source.py
tests/test_array_schedule_source.py
tests/test_list_schedule_source.py

This PR fixes problem of systems with high volume of timed schedules as described in #78.

Added new list-based schedule source.

---

taskiq_redis/redis_broker.py

This PR fixes problem discussed in https://github.com/orgs/taskiq-python/discussions/447#discussioncomment-12865526.
Now redis checks for all unacknowledged messages after receiving new messages.

Fixed unacknowledged messages.

---

taskiq_redis/list_schedule_source.py
taskiq_redis/schedule_source.py
tests/test_list_schedule_source.py

This might help in situation when your project has too many tasks to be sent in current minute and it takes more time to fetch them all.
Also, default `RedisScheduleSource` is now deprecated.

ListShceduleSource now always try to fetch tasks from the past.

---

taskiq_redis/redis_broker.py

The debug message is wrong and always display `Found 3 pending messages in stream XXX`.
It's because the result of `xautoclaim` is a tuple with 3 values. Messages are in the second value.

fix: debug log for pending messages count in RedisStreamBroker

---

taskiq_redis/redis_broker.py
taskiq_redis/redis_cluster_broker.py
taskiq_redis/redis_sentinel_broker.py

Due to #94 and #100 , the ack for `StreamBroker` is wrong as it does not take into account the dynamic queue name and always ack on the "main" queue.
This PR fix that issue.

fix: ack to the right stream in case of dynamic queue name

---

docker-compose.yml

bitnami moved all these images to bitnamilegacy catalog, so the image names were updated
(https://hub.docker.com/r/bitnami/redis)

feat: update bitnami catalog to legacy version
